# Generated by Django 5.0.1 on 2026-01-19 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kategoriya nomi', max_length=100)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('icon', models.CharField(default='📌', help_text='Emoji yoki icon', max_length=50)),
                ('color', models.CharField(default='#3498db', help_text='Rang kodi (hex)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['transaction_type', 'name'],
                'unique_together': {('user', 'name', 'transaction_type')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Tranzaksiya summasi', max_digits=15)),
                ('currency', models.CharField(choices=[('UZS', "UZS - O'zbek so'mi"), ('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('RUB', 'RUB - Russian Ruble')], default='UZS', max_length=3)),
                ('description', models.TextField(blank=True, help_text='Izoh', null=True)),
                ('date', models.DateTimeField(help_text='Tranzaksiya sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(help_text='Qaysi karta/hisobdan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cards.card')),
                ('category', models.ForeignKey(help_text='Tranzaksiya kategoriyasi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
    ]
