# Generated by Django 5.0.1 on 2026-01-19 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Karta nomi', max_length=100)),
                ('card_type', models.CharField(choices=[('cash', 'Cash'), ('debit', 'Debit Card'), ('credit', 'Credit Card'), ('bank_account', 'Bank Account')], max_length=20)),
                ('currency', models.CharField(choices=[('UZS', "UZS - O'zbek so'mi"), ('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('RUB', 'RUB - Russian Ruble')], default='UZS', max_length=3)),
                ('card_number', models.CharField(blank=True, help_text='Karta raqami (ixtiyoriy)', max_length=19, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Joriy balans', max_digits=15)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Kredit limit (faqat credit card uchun)', max_digits=15, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Bank nomi', max_length=100, null=True)),
                ('color', models.CharField(default='#3498db', help_text='Rang kodi (hex)', max_length=7)),
                ('description', models.TextField(blank=True, help_text="Qo'shimcha ma'lumot", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Faol holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
